### ISSUE TITLE
Fragment

### ISSUE THREAD

**Issue by crysan** [campusappcn/AndRouter#1]
Hi!
router.put("fragment://second/:{name}", SecondFragment.class); 
will work?

**Comment by beautifulSoup** [comment]
@crysan What the action do you want when you what to do router.open("framgent://second/:{name}), is it to replace the fragment of the current activity?  I don't realize the feature. If you do want it. you can implement the IRouter interface and add it to RouterManager. Please remember AndRouter is a router framework. You can add any router you want to it. Best wishes.

**Comment by crysan** [comment]
Ty!
