### ISSUE TITLE
不能加载依赖插件

### ISSUE THREAD

**Issue by Yanqilong** [campusappcn/AndRouter#15]
大神，com.github.dcendents:android-maven-gradle-plugin:1.3插件加载不下来，要怎么解决

Error:A problem occurred configuring root project 'AndRouter'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not resolve com.github.dcendents:android-maven-gradle-plugin:1.3.
     Required by:
         :AndRouter:unspecified
      > Could not resolve com.github.dcendents:android-maven-gradle-plugin:1.3.
         > Could not get resource 'https://jcenter.bintray.com/com/github/dcendents/android-maven-gradle-plugin/1.3/android-maven-gradle-plugin-1.3.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/github/dcendents/android-maven-gradle-plugin/1.3/android-maven-gradle-plugin-1.3.pom'.
               > Connection to http://192.168.3.99:7777 refused

**Comment by beautifulSoup** [comment]
哎呀，我的错，把代理文件传上来了， 你更新下版本1.2.7

**Comment by beautifulSoup** [comment]
如果是整个工程的话，你把gradle.properties里面的那几行代理的配置项给去了

**Comment by Yanqilong** [comment]
还有点小问题，好像这个插件com.github.dcendents.android-maven的问题，是1.3版本吗

Error:(3, 0) No service of type Factory<LoggingManagerInternal> available in ProjectScopeServices.
<a href="openFile:D:\Workspace\Github\AndRouter\router\build.gradle">Open File</a>

**Comment by Yanqilong** [comment]
好了，跑起来了，改插件为1.5版本解决了

**Comment by beautifulSoup** [comment]
好的

**Comment by Yanqilong** [comment]
Dada,  could you open a qq group to community some problem?
