### ISSUE TITLE
按配置弄好但是加载不到库

### ISSUE THREAD

**Issue by hnty545** [campusappcn/AndRouter#17]
Error:Could not find com.github.campusappcn.AndRouter:compiler:1.2.4.
Searched in the following locations:
    file:/D:/Mobile/Android/android-sdk/extras/m2repository/com/github/campusappcn/AndRouter/compiler/1.2.4/compiler-1.2.4.pom
    file:/D:/Mobile/Android/android-sdk/extras/m2repository/com/github/campusappcn/AndRouter/compiler/1.2.4/compiler-1.2.4.jar
    file:/D:/Mobile/Android/android-sdk/extras/google/m2repository/com/github/campusappcn/AndRouter/compiler/1.2.4/compiler-1.2.4.pom
    file:/D:/Mobile/Android/android-sdk/extras/google/m2repository/com/github/campusappcn/AndRouter/compiler/1.2.4/compiler-1.2.4.jar
    file:/D:/Mobile/Android/android-sdk/extras/android/m2repository/com/github/campusappcn/AndRouter/compiler/1.2.4/compiler-1.2.4.pom
    file:/D:/Mobile/Android/android-sdk/extras/android/m2repository/com/github/campusappcn/AndRouter/compiler/1.2.4/compiler-1.2.4.jar
    file:/D:/Program Files/Android/Android Studio/gradle/m2repository/com/github/campusappcn/AndRouter/compiler/1.2.4/compiler-1.2.4.pom
    file:/D:/Program Files/Android/Android Studio/gradle/m2repository/com/github/campusappcn/AndRouter/compiler/1.2.4/compiler-1.2.4.jar
    https://jcenter.bintray.com/com/github/campusappcn/AndRouter/compiler/1.2.4/compiler-1.2.4.pom
    https://jcenter.bintray.com/com/github/campusappcn/AndRouter/compiler/1.2.4/compiler-1.2.4.jar
Required by:
    MposFramework:MposFrameworkPay:unspecified

我把1.2.4改成1.2.7也是类似提示
compile 'com.github.campusappcn.AndRouter:router:1.2.4'
apt 'com.github.campusappcn.AndRouter:compiler:1.2.4'

**Comment by beautifulSoup** [comment]
[Install](https://github.com/campusappcn/AndRouter#install)
看一下是不是没有添加jitpack repository的配置
