### ISSUE TITLE
gradle 集成失败问题

### ISSUE THREAD

**Issue by walfud** [campusappcn/AndRouter#9]
hi,. 我们集成总是提示找不到 compiler 这个包, 错误如下:
Error:Could not find com.github.campusappcn.AndRouter:compiler:1.2.5.
Searched in the following locations:
    file:/D:/Android/Android Studio/gradle/m2repository/com/github/campusappcn/AndRouter/compiler/1.2.5/compiler-1.2.5.pom
    file:/D:/Android/Android Studio/gradle/m2repository/com/github/campusappcn/AndRouter/compiler/1.2.5/compiler-1.2.5.jar
    https://jcenter.bintray.com/com/github/campusappcn/AndRouter/compiler/1.2.5/compiler-1.2.5.pom
    https://jcenter.bintray.com/com/github/campusappcn/AndRouter/compiler/1.2.5/compiler-1.2.5.jar
    file:/D:/Android/sdk/extras/android/m2repository/com/github/campusappcn/AndRouter/compiler/1.2.5/compiler-1.2.5.pom
    file:/D:/Android/sdk/extras/android/m2repository/com/github/campusappcn/AndRouter/compiler/1.2.5/compiler-1.2.5.jar
    file:/D:/Android/sdk/extras/google/m2repository/com/github/campusappcn/AndRouter/compiler/1.2.5/compiler-1.2.5.pom
    file:/D:/Android/sdk/extras/google/m2repository/com/github/campusappcn/AndRouter/compiler/1.2.5/compiler-1.2.5.jar
Required by:
    com.licaigc:library:0.6.0

我们的 gradle 文件:

``` gradle

buildscript {
    repositories {
        jcenter()
        mavenCentral()
        maven { url "https://jitpack.io" }
    }

    dependencies {
        ...
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
    }
}

apply plugin: 'android-apt'
...

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.3"

    defaultConfig {
        minSdkVersion 12
        targetSdkVersion 23
        ...
    }
    ....
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    ...
    compile 'com.github.campusappcn.AndRouter:router:1.2.5'
    apt 'com.github.campusappcn.AndRouter:compiler:1.2.5'
}

```

我看了 JitPack 上 1.2.5 版本的 log, 貌似也输出了这个文件. 不知道为什么, 是哪里没配置好呢?

**Comment by beautifulSoup** [comment]
我这边貌似是可以的，我尝试找下原因。。

**Comment by walfud** [comment]
hey, 我发现问题了, 我必须要在 Project/build.gradle 中加入 maven { url ...} 才行. 我在 module/build.gradle 中加入是不行的... 这不应该的.
我再看看是不是加入的位置是否正确

**Comment by beautifulSoup** [comment]
哦，原来你这是一个文件 = ，=。  还有那个repository 应该是放在allprojects节点下的，buildscript是给gradle用的，而这里是表示你的项目依赖于这些repository，所以应该放在allprojects节点下。这是我的项目gradle文件，可以参考下。

```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.1.2'
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        maven {
            url "https://jitpack.io"
        }

        maven {
            url "http://dl.bintray.com/populov/maven"
        }

        maven{
            url 'https://oss.sonatype.org/content/repositories/snapshots/'
        }

        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**Comment by walfud** [comment]
恩, 谢谢你的回复. 
我们的主工程下有多个 module, 我放在 module/build.gradle 中也是为了不污染别的 module. 所以期望能把这个 module 依赖的东西都包在自己内部. 
不过我们的 project 中的多个 module 之间还有相互引用, 所以最终还是不得已要写在 project/build.gradle 中. 
谢谢你热心的回复.

**Comment by beautifulSoup** [comment]
我个人觉得放在project里面没有什么问题。buildscript里面的内容是只跟编译时用的gradle有关系的，表示gradle要依赖这些库，而跟项目本身关系不大。而在allprojects里面只需要加repository，只是表示项目内依赖的库可以从这些仓库里面找，只是标记了一下，也不会更改实际的项目内容，所以不会对moudle的实际内容产生影响。

**Comment by walfud** [comment]
恩, 你说的没错.
